# Generated by Django 3.0.5 on 2020-05-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Фактическая дата оплаты', null=True, verbose_name='Дата оплаты')),
                ('year_period', models.CharField(help_text='Членский взнос за определенный год', max_length=4, verbose_name='Год')),
                ('month_period', models.CharField(blank=True, help_text='Членский взнос за определенный месяц', max_length=7, null=True, verbose_name='Месяц')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Размер членского взноса за сотку (100 м.кв)/рублей', max_digits=7, verbose_name='Размер взноса')),
                ('plot_area', models.PositiveIntegerField(help_text='Площадь участка в метрах квадратных', verbose_name='Площадь участка')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма взноса к оплате', max_digits=7, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('n', 'Неоплачено'), ('p', 'Оплачено'), ('c', 'Оплата подтверждена')], default='n', help_text='Статус записи', max_length=1, verbose_name='Статус')),
                ('land_plot', models.ForeignKey(help_text='Выберите участок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.LandPlot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'членский взнос',
                'verbose_name_plural': 'членские взносы',
            },
        ),
    ]
