# Generated by Django 3.0.2 on 2020-06-02 12:02

from django.db import migrations, models
import django.db.models.deletion
import membership.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, help_text='Фактическая дата оплаты', null=True, verbose_name='Дата оплаты')),
                ('target', models.CharField(help_text='Укажите назначение целевого взноса', max_length=200, verbose_name='Цель')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма взноса к оплате', max_digits=7, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('not_paid', 'Неоплачено'), ('paid', 'Оплачено'), ('payment_confirmed', 'Оплата подтверждена')], default='not_paid', help_text='Статус оплаты', max_length=17, verbose_name='Статус')),
                ('land_plot', models.ForeignKey(help_text='Выберите участок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.LandPlot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'целевой взнос',
                'verbose_name_plural': 'целевые взносы',
            },
        ),
        migrations.CreateModel(
            name='MRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Укажите дату ввода тарифа', verbose_name='Дата')),
                ('year_period', models.CharField(help_text='Укажите год периода для произведения расчета в виде 4-х значного числа', max_length=4, validators=[membership.validators.validate_number, membership.validators.validate_year_period_min_length], verbose_name='Год')),
                ('month_period', models.CharField(blank=True, choices=[('', ''), ('Jan', 'Январь'), ('Feb', 'Февраль'), ('Mar', 'Март'), ('Apr', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Aug', 'Август'), ('Sep', 'Сентябрь'), ('Oct', 'Октябрь'), ('Nov', 'Ноябрь'), ('Dec', 'Декабрь')], default='', help_text='Выберите месяц, если начисления членских взносов расчитываются помесячно', max_length=3, verbose_name='Месяц')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Укажите размер членского взноса для выбранного периода в рублях за сотку (100 м.кв)', max_digits=7, verbose_name='Размер взноса')),
                ('snt', models.ForeignKey(help_text='Выберите СНТ для которого будет применен тариф', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Snt', verbose_name='СНТ')),
            ],
            options={
                'verbose_name': 'Тариф (членский взнос)',
                'verbose_name_plural': 'Тарифы (членский взнос)',
            },
        ),
        migrations.CreateModel(
            name='MPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, help_text='Фактическая дата оплаты', null=True, verbose_name='Дата оплаты')),
                ('year_period', models.CharField(help_text='Укажите год в виде 4-х значного числа', max_length=4, validators=[membership.validators.validate_number, membership.validators.validate_year_period_min_length], verbose_name='Год')),
                ('month_period', models.CharField(blank=True, choices=[('', ''), ('Jan', 'Январь'), ('Feb', 'Февраль'), ('Mar', 'Март'), ('Apr', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Aug', 'Август'), ('Sep', 'Сентябрь'), ('Oct', 'Октябрь'), ('Nov', 'Ноябрь'), ('Dec', 'Декабрь')], default='', help_text='Выберите месяц, если начисления членских взносов расчитываются помесячно', max_length=3, verbose_name='Месяц')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Размер членского взноса за сотку (100 м.кв)/рублей', max_digits=7, verbose_name='Размер взноса')),
                ('plot_area', models.PositiveIntegerField(help_text='Площадь участка в квадратных метрах', verbose_name='Площадь участка')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма взноса к оплате', max_digits=7, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('not_paid', 'Неоплачено'), ('paid', 'Оплачено'), ('payment_confirmed', 'Оплата подтверждена')], default='not_paid', help_text='Статус оплаты', max_length=17, verbose_name='Статус')),
                ('land_plot', models.ForeignKey(help_text='Выберите участок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.LandPlot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'членский взнос',
                'verbose_name_plural': 'членские взносы',
            },
        ),
        migrations.AddConstraint(
            model_name='tpayment',
            constraint=models.UniqueConstraint(fields=('target', 'land_plot'), name='membership_tpayment_target_land_plot_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='mrate',
            constraint=models.UniqueConstraint(fields=('year_period', 'month_period'), name='membership_mrate_year_month_period_constraint'),
        ),
        migrations.AddConstraint(
            model_name='mpayment',
            constraint=models.UniqueConstraint(fields=('year_period', 'month_period', 'land_plot'), name='membership_mpayment_year_month_period_land_plot_unique_constraint'),
        ),
    ]
