# Generated by Django 3.0.5 on 2020-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mpayment',
            name='unique membership payment',
        ),
        migrations.RemoveConstraint(
            model_name='mrate',
            name='unique membership rate',
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='status',
            field=models.CharField(choices=[('n', 'Неоплачено'), ('p', 'Оплачено'), ('c', 'Оплата подтверждена')], default='n', help_text='Статус оплаты', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='mpayment',
            constraint=models.UniqueConstraint(fields=('year_period', 'month_period'), name='membership_mpayment_year_month_period_constraint'),
        ),
        migrations.AddConstraint(
            model_name='mrate',
            constraint=models.UniqueConstraint(fields=('year_period', 'month_period'), name='membership_mrate_year_month_period_constraint'),
        ),
    ]
