# Generated by Django 3.0.2 on 2020-05-21 12:40

from django.db import migrations, models
import django.db.models.deletion
import membership.validators


class Migration(migrations.Migration):

    dependencies = [
        ('index', '__first__'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpayment',
            name='month_period',
            field=models.CharField(blank=True, choices=[('', ''), ('Jan', 'Январь'), ('Feb', 'Февраль'), ('Mar', 'Март'), ('Apr', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Aug', 'Август'), ('Sep', 'Сентябрь'), ('Oct', 'Октябрь'), ('Nov', 'Ноябрь'), ('Dec', 'Декабрь')], default='', help_text='Выберите месяц, если начисления членских взносов расчитываются помесячно', max_length=3, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Фактическая дата оплаты', null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='plot_area',
            field=models.PositiveIntegerField(help_text='Площадь участка в квадратных метрах', verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='year_period',
            field=models.CharField(help_text='Укажите год в виде 4-х значного числа', max_length=4, validators=[membership.validators.validate_number, membership.validators.validate_year_period_min_length], verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='MRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Укажите дату ввода тарифа', verbose_name='Дата')),
                ('year_period', models.CharField(help_text='Укажите год периода для произведения расчета в виде 4-х значного числа', max_length=4, validators=[membership.validators.validate_number, membership.validators.validate_year_period_min_length], verbose_name='Год')),
                ('month_period', models.CharField(blank=True, choices=[('', ''), ('Jan', 'Январь'), ('Feb', 'Февраль'), ('Mar', 'Март'), ('Apr', 'Апрель'), ('May', 'Май'), ('Jun', 'Июнь'), ('Jul', 'Июль'), ('Aug', 'Август'), ('Sep', 'Сентябрь'), ('Oct', 'Октябрь'), ('Nov', 'Ноябрь'), ('Dec', 'Декабрь')], default='', help_text='Выберите месяц, если начисления членских взносов расчитываются помесячно', max_length=3, verbose_name='Месяц')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Укажите размер членского взноса для выбранного периода в рублях за сотку (100 м.кв)', max_digits=7, verbose_name='Размер взноса')),
                ('snt', models.ForeignKey(help_text='Укажите СНТ для которого будет применен тариф', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Snt', verbose_name='СНТ')),
            ],
            options={
                'verbose_name': 'Тариф (членский взнос)',
                'verbose_name_plural': 'Тарифы (членский взнос)',
            },
        ),
        migrations.AddConstraint(
            model_name='mrate',
            constraint=models.UniqueConstraint(fields=('year_period', 'month_period'), name='unique membership rate'),
        ),
    ]
