# Generated by Django 3.0.5 on 2020-05-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '__first__'),
        ('membership', '0002_auto_20200521_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, help_text='Фактическая дата оплаты', null=True, verbose_name='Дата оплаты')),
                ('target', models.CharField(help_text='Укажите назначение целевого взноса', max_length=200, verbose_name='Цель')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма взноса к оплате', max_digits=7, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('n', 'Неоплачено'), ('p', 'Оплачено'), ('c', 'Оплата подтверждена')], default='n', help_text='Статус оплаты', max_length=1, verbose_name='Статус')),
                ('land_plot', models.ForeignKey(help_text='Выберите участок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.LandPlot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'целевой взнос',
                'verbose_name_plural': 'целевые взносы',
            },
        ),
    ]
