# Generated by Django 3.0.5 on 2020-05-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'счетчик эл.энергии',
                'verbose_name_plural': 'счетчики эл.энергии',
            },
        ),
    ]
