# Generated by Django 3.0.5 on 2020-05-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecounterrecord',
            options={'verbose_name': 'показания э/счетчика', 'verbose_name_plural': 'показания э/счетчиков'},
        ),
        migrations.AlterModelOptions(
            name='erate',
            options={'verbose_name': 'тариф на э/энергию', 'verbose_name_plural': 'тарифы на э/энергию'},
        ),
    ]
