# Generated by Django 3.0.2 on 2020-06-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecounterrecord',
            name='e_counter',
            field=models.ForeignKey(help_text='Выберите счетчик', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electricity.ECounter', verbose_name='Счетчик'),
        ),
    ]
