# Generated by Django 3.0.5 on 2020-05-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_auto_20200526_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erate',
            options={'verbose_name': 'тариф за э/энергию', 'verbose_name_plural': 'тарифы за э/энергию'},
        ),
    ]
