# Generated by Django 3.0.5 on 2020-05-18 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, validators=[index.models.validate_human_names], verbose_name='Имя')),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=50, validators=[index.models.validate_human_names], verbose_name='Отчество')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, validators=[index.models.validate_human_names], verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'председатель',
                'verbose_name_plural': 'председатели',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='Snt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название СНТ', max_length=200, verbose_name='Название СНТ')),
                ('personal_acc', models.CharField(help_text='Номер расчетного счета (20-и значное число)', max_length=20, validators=[index.models.validate_number, index.models.validate_20_length], verbose_name='Номер расчетного счета')),
                ('bank_name', models.CharField(help_text='Наименование банка получателя', max_length=45, verbose_name='Наименование банка получателя')),
                ('bic', models.CharField(help_text='БИК (9-и значное число)', max_length=9, validators=[index.models.validate_number, index.models.validate_9_length], verbose_name='БИК')),
                ('corresp_acc', models.CharField(help_text='Номер кор./счета (20-и значное число)', max_length=20, validators=[index.models.validate_number, index.models.validate_20_length], verbose_name='Номер кор./счета')),
                ('inn', models.CharField(help_text='ИНН (10-и значное число)', max_length=10, validators=[index.models.validate_number, index.models.validate_10_length], verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='КПП (9-и значное число)', max_length=9, validators=[index.models.validate_number, index.models.validate_9_length], verbose_name='КПП')),
                ('address', models.CharField(help_text='Полный адрес садоводства включая область и р-он', max_length=200, verbose_name='Адрес')),
                ('chair_man', models.OneToOneField(help_text='председатель садоводства', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.ChairMan', verbose_name='председатель')),
            ],
            options={
                'verbose_name': 'СНТ',
                'verbose_name_plural': 'СНТ',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, validators=[index.models.validate_human_names], verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, validators=[index.models.validate_human_names], verbose_name='Имя')),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=50, validators=[index.models.validate_human_names], verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, help_text='Введите телефон в формате +7xxxxxxxxx', max_length=12, null=True, unique=True, validators=[index.models.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Адрес электронной почты', max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('user', models.OneToOneField(blank=True, help_text='Аккаунт пользователя на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(help_text='Номер участка', max_length=10, unique=True, verbose_name='Номер участка')),
                ('plot_area', models.PositiveIntegerField(help_text='Единица измерения кв.м', verbose_name='Размер участка')),
                ('owner', models.ForeignKey(help_text='Владелец участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Owner', verbose_name='владелец участка')),
                ('snt', models.ForeignKey(help_text='Расположен в СНТ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Snt', verbose_name='СНТ')),
            ],
            options={
                'verbose_name': 'участок',
                'verbose_name_plural': 'участки',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации', verbose_name='Дата публикации')),
                ('title', models.CharField(help_text='Заголовок объявления', max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Текст объявления', verbose_name='Текст')),
                ('author', models.ForeignKey(help_text='Автор объявления (действующий председатель)', on_delete=django.db.models.deletion.CASCADE, to='index.ChairMan', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
    ]
