# Generated by Django 3.0.5 on 2020-05-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('el_pay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, validators=[index.models.validate_human_names], verbose_name='Имя')),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=50, validators=[index.models.validate_human_names], verbose_name='Отчество')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, validators=[index.models.validate_human_names], verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'председатель',
                'verbose_name_plural': 'председатели',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, validators=[index.models.validate_human_names], verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, validators=[index.models.validate_human_names], verbose_name='Имя')),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=50, validators=[index.models.validate_human_names], verbose_name='Отчество')),
                ('status', models.CharField(choices=[('c', 'Настоящий'), ('p', 'Прежний')], default='c', help_text='Статус владельца', max_length=1, verbose_name='Статус владельца')),
                ('start_owner_date', models.DateField(verbose_name='дата начала владения')),
                ('end_owner_date', models.DateField(blank=True, null=True, verbose_name='дата окончания владения')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
            },
        ),
        migrations.CreateModel(
            name='Snt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название СНТ', max_length=200, verbose_name='Название СНТ')),
                ('personal_acc', models.CharField(help_text='Номер расчетного счета (20-и значное число)', max_length=20, validators=[index.models.validate_number, index.models.validate_20_length], verbose_name='Номер расчетного счета')),
                ('bank_name', models.CharField(help_text='Наименование банка получателя', max_length=45, verbose_name='Наименование банка получателя')),
                ('bic', models.CharField(help_text='БИК (9-и значное число)', max_length=9, validators=[index.models.validate_number, index.models.validate_9_length], verbose_name='БИК')),
                ('corresp_acc', models.CharField(help_text='Номер кор./счета (20-и значное число)', max_length=20, validators=[index.models.validate_number, index.models.validate_20_length], verbose_name='Номер кор./счета')),
                ('inn', models.CharField(help_text='ИНН (10-и значное число)', max_length=10, validators=[index.models.validate_number, index.models.validate_10_length], verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='КПП (9-и значное число)', max_length=9, validators=[index.models.validate_number, index.models.validate_9_length], verbose_name='КПП')),
                ('chair_man', models.OneToOneField(help_text='Председатель садоводства', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.ChairMan', verbose_name='председатель')),
            ],
            options={
                'verbose_name': 'СНТ',
                'verbose_name_plural': 'СНТ',
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(help_text='Номер участка', max_length=10, unique=True, verbose_name='Номер участка')),
                ('plot_area', models.PositiveIntegerField(help_text='Единица измерения кв.м', verbose_name='Размер участка')),
                ('electrical_counter', models.OneToOneField(help_text='Данные прибора учета электроэнергии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_pay.ElectricalCounter', verbose_name='Счетчик')),
                ('owner', models.ForeignKey(help_text='Владелец участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Owner', verbose_name='владелец участка')),
                ('snt', models.ForeignKey(help_text='Расположен в СНТ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Snt', verbose_name='СНТ')),
                ('user', models.ForeignKey(blank=True, help_text='Аккаунт пользователя на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'участок',
                'verbose_name_plural': 'участки',
            },
        ),
    ]
