# Generated by Django 3.0.2 on 2020-05-15 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landplot',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Аккаунт пользователя на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='snt',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Полный адрес садоводства включая область и р-он', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
