# Generated by Django 3.0.5 on 2020-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chairman',
            constraint=models.UniqueConstraint(fields=('join_date',), name='index_chairman_join_date_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='chairman',
            constraint=models.UniqueConstraint(fields=('leave_date',), name='index_chairman_leave_date_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='chairman',
            constraint=models.UniqueConstraint(condition=models.Q(('join_date__isnull', False), ('leave_date__isnull', True)), fields=('join_date', 'leave_date'), name='index_chairman_join_date_not_null_leave_date_null_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(condition=models.Q(('join_date__isnull', False), ('leave_date__isnull', True)), fields=('last_name', 'first_name', 'middle_name', 'join_date', 'leave_date'), name='index_owner_active_owner_duplicate_constraint'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('email',), name='index_owner_email_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('phone',), name='index_owner_phone_unique_constraint'),
        ),
    ]
