# Generated by Django 3.0.5 on 2020-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200526_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('unpublished', 'Неопубликовано')], default='unpublished', help_text='Выберите статус для публикации или снятия с публикации', max_length=11, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='accountant',
            constraint=models.UniqueConstraint(condition=models.Q(('join_date__isnull', False), ('leave_date__isnull', True)), fields=('join_date', 'leave_date'), name='index_accountant_join_date_not_null_leave_date_null_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='accountant',
            constraint=models.UniqueConstraint(fields=('email',), name='index_accountant_email_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='accountant',
            constraint=models.UniqueConstraint(fields=('phone',), name='index_accountant_phone_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='landplot',
            constraint=models.UniqueConstraint(fields=('plot_number',), name='index_landplot_plot_number_unique_constraint'),
        ),
    ]
