# Generated by Django 3.0.5 on 2020-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200526_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('unpublished', 'Неопубликовано')], default='unpublished', help_text='Выберите статус для публикации или снятия с публикации', max_length=11, verbose_name='Статус'),
        ),
    ]
